/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import entidades.Queja;
import entidades.VisitaGuiada;
import fachada.FacadeNegocio;
import interfaces.INegocio;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.types.ObjectId;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author alanf
 */
public class FrmAtencionVisitantes extends javax.swing.JFrame {

    /**
     * Creates new form FrmAtencionVisitantes
     */
    public FrmAtencionVisitantes() {
        initComponents();
        this.negocio = new FacadeNegocio();
    }
    
    private INegocio negocio;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAtencionVisitantes = new javax.swing.JPanel();
        PnlAtencionVisitantes = new javax.swing.JPanel();
        pnlEncabezado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        pnlItinerarios = new javax.swing.JScrollPane();
        tbltinerario = new javax.swing.JTable();
        lblItinerario = new javax.swing.JLabel();
        lblQueja = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoQueja = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        lblDATOS = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnEnviarQueja = new javax.swing.JButton();
        btnRegistrarQueja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnlAtencionVisitantes.setName(""); // NOI18N
        PnlAtencionVisitantes.setPreferredSize(new java.awt.Dimension(1117, 606));

        pnlEncabezado.setBackground(new java.awt.Color(33, 47, 69));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 204, 204));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Formulario de quejas");

        btnMenu.setText("MENÚ");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbltinerario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Horario", "Duracion", "Guia", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltinerario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbltinerarioMousePressed(evt);
            }
        });
        pnlItinerarios.setViewportView(tbltinerario);

        lblItinerario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblItinerario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItinerario.setText("Itinerario");

        lblQueja.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblQueja.setText("Escribe tu queja aquí");

        campoQueja.setColumns(20);
        campoQueja.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        campoQueja.setRows(5);
        jScrollPane1.setViewportView(campoQueja);

        lblDATOS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDATOS.setText("Tus datos:");

        lblEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblEmail.setText("E-mail: (*)");

        lblTelefono.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTelefono.setText("Telefono: (*)");

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombre.setText("Nombre: (op)");

        btnEnviarQueja.setText("Enviar queja");
        btnEnviarQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarQuejaActionPerformed(evt);
            }
        });

        btnRegistrarQueja.setText("Registrar queja");
        btnRegistrarQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarQuejaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlAtencionVisitantesLayout = new javax.swing.GroupLayout(PnlAtencionVisitantes);
        PnlAtencionVisitantes.setLayout(PnlAtencionVisitantesLayout);
        PnlAtencionVisitantesLayout.setHorizontalGroup(
            PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                                .addComponent(lblQueja)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDATOS)
                            .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                                .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelefono)
                                    .addComponent(lblEmail)
                                    .addComponent(lblNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlAtencionVisitantesLayout.createSequentialGroup()
                                .addComponent(btnRegistrarQueja)
                                .addGap(66, 66, 66)
                                .addComponent(btnEnviarQueja)))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlAtencionVisitantesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(pnlItinerarios, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(lblItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlAtencionVisitantesLayout.setVerticalGroup(
            PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblItinerario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlItinerarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                        .addComponent(lblQueja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(PnlAtencionVisitantesLayout.createSequentialGroup()
                        .addComponent(lblDATOS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(PnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEnviarQueja)
                            .addComponent(btnRegistrarQueja))
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout pnlAtencionVisitantesLayout = new javax.swing.GroupLayout(pnlAtencionVisitantes);
        pnlAtencionVisitantes.setLayout(pnlAtencionVisitantesLayout);
        pnlAtencionVisitantesLayout.setHorizontalGroup(
            pnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtencionVisitantesLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(PnlAtencionVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAtencionVisitantesLayout.setVerticalGroup(
            pnlAtencionVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtencionVisitantesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PnlAtencionVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAtencionVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAtencionVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Metodos
    public List<VisitaGuiada> consultarVisitasGuiadasMes(){
       return negocio.consultarMes();
    }
    
public String getItinerarioSeleccionado(){
String itinerarioSeleccionado ="";
int indiceFila = this.tbltinerario.getSelectedRow();
if (indiceFila != -1) {
            int indiceColumnaNombre = 0;
            int indiceColumnaGuia = 3;
            int indiceColumnaFecha = 4;
            DefaultTableModel modeloTabla = (DefaultTableModel) this.tbltinerario.getModel();
            String nombre = (String) modeloTabla.getValueAt(indiceFila, indiceColumnaNombre);
            String guia = (String) modeloTabla.getValueAt(indiceFila, indiceColumnaGuia);
            String fecha = (String) modeloTabla.getValueAt(indiceFila, indiceColumnaFecha);
            itinerarioSeleccionado = nombre+ ", "+guia+", "+fecha; 
            
            return itinerarioSeleccionado;
        } else {
            return null;
        }
}

public void guardarQueja(){
    Queja queja = new Queja();
    String itinerario = this.getItinerarioSeleccionado();
    String textoQueja = this.campoQueja.getText();
    String email = this.txtEmail.getText();
    String numeroTelefonico = this.txtTelefono.getText();
    String nombre = this.txtNombre.getText();
    
    queja.setItinerario(itinerario);
    queja.setQueja(textoQueja);
    queja.setEmail(email);
    queja.setNumeroTelefonico(numeroTelefonico);
    queja.setNombre(nombre);
    
    boolean seGuardo =negocio.guardarQueja(queja);
    if(seGuardo){
        JOptionPane.showMessageDialog(this, "La queja se a enviado con exito, sera leida y atendida a la brevedad.", "información", JOptionPane.INFORMATION_MESSAGE);
        this.limpiarFormulario();
    }
}

    
    public void limpiarFormulario(){
        this.campoQueja.setText("");
        this.txtEmail.setText("");
        this.txtNombre.setText("");
        this.txtTelefono.setText("");
        DefaultTableModel modeloTabla = (DefaultTableModel) this.tbltinerario.getModel();
         modeloTabla.setRowCount(0);
    }
    
    public void llenarTablaNombreItinerario(List <VisitaGuiada> itinerarios){
        
        List<VisitaGuiada> listaVisitas = itinerarios;
        
         DefaultTableModel modeloTabla = (DefaultTableModel) this.tbltinerario.getModel();
         modeloTabla.setRowCount(0);
         
         listaVisitas.forEach(visita->{
          
         Date fechaVisita = visita.getInicio();
         int anio = fechaVisita.getYear()+1900;
         int mes = fechaVisita.getMonth()+1;
         int dia= fechaVisita.getDate();    
         String fechaFormato = anio+"/"+mes+"/"+dia;
             
         Object[] fila = new Object[5];
         fila[0] = visita.getItinerario().get(0).getNombre();
         fila[1] = visita.getItinerario().get(0).getDiasHorario();
         fila[2] = visita.getItinerario().get(0).getDuracion();
         fila[3] = visita.getGuia().getNombre();
         fila[4] = fechaFormato;
         modeloTabla.addRow(fila);
         });
    }
    
    
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrmPrincipal principal = new FrmPrincipal();
        principal.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    
    
    private void btnRegistrarQuejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarQuejaActionPerformed
        // TODO add your handling code here:
        this.llenarTablaNombreItinerario(this.consultarVisitasGuiadasMes());
    }//GEN-LAST:event_btnRegistrarQuejaActionPerformed

    private void tbltinerarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltinerarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbltinerarioMousePressed

    private void btnEnviarQuejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarQuejaActionPerformed
        // TODO add your handling code here:
        this.guardarQueja();
    }//GEN-LAST:event_btnEnviarQuejaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlAtencionVisitantes;
    private javax.swing.JButton btnEnviarQueja;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrarQueja;
    private javax.swing.JTextArea campoQueja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDATOS;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblItinerario;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblQueja;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAtencionVisitantes;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JScrollPane pnlItinerarios;
    private javax.swing.JTable tbltinerario;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
