package pantallas;

import java.awt.CardLayout;

/**
 * Interfaz Gráfica de Usuario principal para el control del sistema de zoológico
 *  
 * @author Marin
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private FrmHabitats habitatsFrom;
    
    /**
     * Constructor por defecto
     */
    public FrmPrincipal() {
        initComponents();
        
        this.habitatsFrom = new FrmHabitats();
        pnlContenido.add(habitatsFrom , "Habitats");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuPrincipal = new javax.swing.JPanel();
        lblTituloPrincipal = new javax.swing.JLabel();
        btnRegistroHabitat = new javax.swing.JButton();
        pnlApp = new javax.swing.JPanel();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblTituloPrincipal.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        lblTituloPrincipal.setText("ZOOLÓGICO");

        btnRegistroHabitat.setText("Registro Hábitats");
        btnRegistroHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistroHabitats(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuPrincipalLayout = new javax.swing.GroupLayout(pnlMenuPrincipal);
        pnlMenuPrincipal.setLayout(pnlMenuPrincipalLayout);
        pnlMenuPrincipalLayout.setHorizontalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(btnRegistroHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(lblTituloPrincipal)))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        pnlMenuPrincipalLayout.setVerticalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblTituloPrincipal)
                .addGap(197, 197, 197)
                .addComponent(btnRegistroHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenuPrincipal, "Menu");

        pnlContenido.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlAppLayout = new javax.swing.GroupLayout(pnlApp);
        pnlApp.setLayout(pnlAppLayout);
        pnlAppLayout.setHorizontalGroup(
            pnlAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAppLayout.setVerticalGroup(
            pnlAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlApp, "App");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickBtnRegistroHabitats(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistroHabitats
        CardLayout cl = (CardLayout)(this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "App");
        
        cl = (CardLayout)(pnlContenido.getLayout());
        cl.show(pnlContenido, "Habitats");
    }//GEN-LAST:event_clickBtnRegistroHabitats


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroHabitat;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JPanel pnlApp;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
