package pantallas;

import java.awt.CardLayout;

/**
 * Interfaz Gráfica de Usuario principal para el control del sistema de zoológico
 *  
 * @author Marin
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private FrmHabitats habitatsFrom;
    private FrmItinerarios itinerariosForm;
    private FrmEspecies especiesForm;
    
    /**
     * Constructor por defecto
     */
    public FrmPrincipal() {
        initComponents();
        
        this.habitatsFrom = new FrmHabitats();
        pnlContenido.add(habitatsFrom , "Habitats");
        
        this.itinerariosForm = new FrmItinerarios();
        pnlContenido.add(itinerariosForm , "Itinerarios");
        
        this.especiesForm = new FrmEspecies();
        pnlContenido.add(especiesForm , "Especies");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuPrincipal = new javax.swing.JPanel();
        lblTituloPrincipal = new javax.swing.JLabel();
        btnRegistroHabitat = new javax.swing.JButton();
        btnRegistroItinerarios = new javax.swing.JButton();
        btnRegistrarQueja = new javax.swing.JButton();
        btnRegistrarEspecie = new javax.swing.JButton();
        pnlApp = new javax.swing.JPanel();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblTituloPrincipal.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        lblTituloPrincipal.setText("ZOOLÓGICO");

        btnRegistroHabitat.setText("Registro Hábitats");
        btnRegistroHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistroHabitats(evt);
            }
        });

        btnRegistroItinerarios.setText("Registro Itinerarios");
        btnRegistroItinerarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistroItinerariosActionPerformed(evt);
            }
        });

        btnRegistrarQueja.setText("Registrar Queja");
        btnRegistrarQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistrarQueja(evt);
            }
        });

        btnRegistrarEspecie.setText("Registrar Especie");
        btnRegistrarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistrarEspecie(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuPrincipalLayout = new javax.swing.GroupLayout(pnlMenuPrincipal);
        pnlMenuPrincipal.setLayout(pnlMenuPrincipalLayout);
        pnlMenuPrincipalLayout.setHorizontalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnRegistroItinerarios, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnRegistroHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnRegistrarQueja, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnRegistrarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(lblTituloPrincipal)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        pnlMenuPrincipalLayout.setVerticalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblTituloPrincipal)
                .addGap(197, 197, 197)
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnRegistroHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroItinerarios, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarQueja, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMenuPrincipal, "Menu");

        pnlContenido.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlAppLayout = new javax.swing.GroupLayout(pnlApp);
        pnlApp.setLayout(pnlAppLayout);
        pnlAppLayout.setHorizontalGroup(
            pnlAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 1115, Short.MAX_VALUE)
        );
        pnlAppLayout.setVerticalGroup(
            pnlAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        getContentPane().add(pnlApp, "App");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickBtnRegistroHabitats(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistroHabitats
        CardLayout cl = (CardLayout)(this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "App");
        
        cl = (CardLayout)(pnlContenido.getLayout());
        cl.show(pnlContenido, "Habitats");
        
    }//GEN-LAST:event_clickBtnRegistroHabitats

    private void clickBtnRegistroItinerariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistroItinerariosActionPerformed
        CardLayout cl = (CardLayout)(this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "App");
        
        cl = (CardLayout)(pnlContenido.getLayout());
        cl.show(pnlContenido, "Itinerarios");
    }//GEN-LAST:event_clickBtnRegistroItinerariosActionPerformed

    private void clickBtnRegistrarQueja(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistrarQueja
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmAtencionVisitantes().setVisible(true);
    }//GEN-LAST:event_clickBtnRegistrarQueja

    private void clickBtnRegistrarEspecie(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistrarEspecie
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "App");

        cl = (CardLayout) (pnlContenido.getLayout());
        cl.show(pnlContenido, "Especies");
    }//GEN-LAST:event_clickBtnRegistrarEspecie


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarEspecie;
    private javax.swing.JButton btnRegistrarQueja;
    private javax.swing.JButton btnRegistroHabitat;
    private javax.swing.JButton btnRegistroItinerarios;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JPanel pnlApp;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
