package pantallas;

import fachada.FacadeNegocio;
import interfaces.INegocio;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 * Frame principal de la aplicación que contiene el menú para acceder a las demás
 * pantallas; el frame almacena todas las pantallas utilizando un CardLayout.
 *  
 * @author Marin
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private FrmHabitats habitatsFrom;
    private FrmItinerarios itinerariosForm;
    private FrmEspecies especiesForm;
    private INegocio negocio;
    
    /**
     * Constructor por defecto.
     */
    public FrmPrincipal() {
        initComponents();
        initNegocio();
    }
    
    /**
     * Inicializa el objeto negocio de tipo INegocio para suministrarlo a las interfaces.
     */
    public void initNegocio(){
        try{
            negocio = new FacadeNegocio();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al conectar con los demás subsistemas." , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuPrincipal = new javax.swing.JPanel();
        lblTituloPrincipal = new javax.swing.JLabel();
        btnRegistroHabitat = new javax.swing.JButton();
        btnRegistroItinerarios = new javax.swing.JButton();
        btnRegistrarQueja = new javax.swing.JButton();
        btnRegistrarEspecie = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        pnlApp = new javax.swing.JPanel();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        lblTituloPrincipal.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        lblTituloPrincipal.setText("ZOOLÓGICO");

        btnRegistroHabitat.setText("Registro Hábitats");
        btnRegistroHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistroHabitats(evt);
            }
        });

        btnRegistroItinerarios.setText("Registro Itinerarios");
        btnRegistroItinerarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistroItinerariosActionPerformed(evt);
            }
        });

        btnRegistrarQueja.setText("Registrar Queja");
        btnRegistrarQueja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistrarQueja(evt);
            }
        });

        btnRegistrarEspecie.setText("Registrar Especie");
        btnRegistrarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnRegistrarEspecie(evt);
            }
        });

        btnAcercaDe.setText("Acerca De");
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickBtnAcercaDe(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuPrincipalLayout = new javax.swing.GroupLayout(pnlMenuPrincipal);
        pnlMenuPrincipal.setLayout(pnlMenuPrincipalLayout);
        pnlMenuPrincipalLayout.setHorizontalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(btnRegistroItinerarios, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(btnRegistroHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnRegistrarQueja, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btnRegistrarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                                .addGap(419, 419, 419)
                                .addComponent(lblTituloPrincipal)))
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAcercaDe)))
                .addContainerGap())
        );
        pnlMenuPrincipalLayout.setVerticalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblTituloPrincipal)
                .addGap(197, 197, 197)
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnRegistroHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistroItinerarios, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarQueja, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnAcercaDe)
                .addContainerGap())
        );

        getContentPane().add(pnlMenuPrincipal, "Menu");

        pnlContenido.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout pnlAppLayout = new javax.swing.GroupLayout(pnlApp);
        pnlApp.setLayout(pnlAppLayout);
        pnlAppLayout.setHorizontalGroup(
            pnlAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        pnlAppLayout.setVerticalGroup(
            pnlAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        getContentPane().add(pnlApp, "App");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Activa el formulario de registro de Hábitats
     * 
     * @param evt Botón de Hábitats seleccionado.
     */
    private void clickBtnRegistroHabitats(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistroHabitats

        if (this.habitatsFrom == null) {
            this.habitatsFrom = new FrmHabitats(negocio);
            pnlContenido.add(habitatsFrom, "Habitats");
        }

        CardLayout cl = (CardLayout)(this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "App");
        
        cl = (CardLayout)(pnlContenido.getLayout());
        cl.show(pnlContenido, "Habitats");
        
    }//GEN-LAST:event_clickBtnRegistroHabitats

    /**
     * Activa el formulario de registro de Itinerarios.
     * 
     * @param evt Botón de Itinerarios seleccionado.
     */
    private void clickBtnRegistroItinerariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistroItinerariosActionPerformed

        if (this.itinerariosForm == null) {
            this.itinerariosForm = new FrmItinerarios(negocio);
            pnlContenido.add(itinerariosForm, "Itinerarios");
        }
        
        CardLayout cl = (CardLayout)(this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "App");
        
        cl = (CardLayout)(pnlContenido.getLayout());
        cl.show(pnlContenido, "Itinerarios");
    }//GEN-LAST:event_clickBtnRegistroItinerariosActionPerformed

    /**
     * Activa el subsistema de atención a clientes para el registro de quejas.
     * 
     * @param evt Botón de Quejas seleccionado.
     */
    private void clickBtnRegistrarQueja(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistrarQueja
        // TODO add your handling code here:
        this.setVisible(false);
        new FrmAtencionVisitantes().setVisible(true);
    }//GEN-LAST:event_clickBtnRegistrarQueja

    /**
     * Activa el formulario de registro de Especies.
     * 
     * @param evt Botón de Especies seleccionado.
     */
    private void clickBtnRegistrarEspecie(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnRegistrarEspecie
        
        if (this.especiesForm == null) {
            this.especiesForm = new FrmEspecies(negocio);
            pnlContenido.add(especiesForm, "Especies");
        }
        
        CardLayout cl = (CardLayout) (this.getContentPane().getLayout());
        cl.show(this.getContentPane(), "App");

        especiesForm.cargarRecursos();
        
        cl = (CardLayout) (pnlContenido.getLayout());
        cl.show(pnlContenido, "Especies");
        
    }//GEN-LAST:event_clickBtnRegistrarEspecie

    /**
     * Muestra una ventana emergente con los nombres de los desarrolladores.
     * 
     * @param evt Botón "acerca de" seleccionado.
     */
    private void clickBtnAcercaDe(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickBtnAcercaDe
        JOptionPane.showMessageDialog(this, "Aplicación desarrollada por: \n Luis Angel Marín Figueroa - 00000228968 \n Ricardo Javier Saavedra Negrete - 00000229351 \n Alan Francisco Gonzalez Angulo - 00000228779" , "Acerca De", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_clickBtnAcercaDe


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnRegistrarEspecie;
    private javax.swing.JButton btnRegistrarQueja;
    private javax.swing.JButton btnRegistroHabitat;
    private javax.swing.JButton btnRegistroItinerarios;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JPanel pnlApp;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
